version: '3'
services:

  caddyx:
    build:
      context: ../von-lcrb-agent
      dockerfile: Dockerfile.caddy
    environment:
      TOB_API_URL: ${TOB_API_URL:-}
      WEB_BASE_HREF: ${WEB_BASE_HREF:-/}
      WEB_HOST_NAME: ${WEB_HOST_NAME:-0.0.0.0}
      WEB_HOST_PORT: ${WEB_HOST_PORT:-8080}
      WEB_HOST_TLS: ${WEB_HOST_TLS:-off}
      AGENT_HOST: ${AGENT_HOST:-agent}
      AGENT_PORT: ${AGENT_PORT:-8000}
    links:
      - myorg-agent:agent
    networks:
      - myorg
    ports:
      - ${WEB_HTTP_PORT:-5000}:${WEB_HOST_PORT:-8080}
    volumes:
      - caddyx-data:/root/.caddy
      - caddyx-logs:/srv/logs

  myorg-agent:
    build:
      context: ../von-lcrb-agent
      dockerfile: Dockerfile
    environment:
      APPLICATION_URL: ${APPLICATION_URL:-http://localhost:5001}
      ENDPOINT_URL: ${ENDPOINT_URL:-http://localhost:5001}
      CONFIG_ROOT: ../config
      ENVIRONMENT: ${ENVIRONMENT:-default}
      ENABLE_GUNICORN: ${ENABLE_GUNICORN:-0}
      INDY_LEDGER_URL: ${LEDGER_URL:-http://localhost:9000}
      FORMS: ${FORMS:-}
      ISSUERS: ${ISSUERS:-}
      LOG_LEVEL: ${LOG_LEVEL:-}
      PYTHON_ENV: ${PYTHON_ENV:-development}
      TOB_API_URL: ${TOB_API_URL:-}
      TOB_APP_URL: ${TOB_APP_URL:-}
      WALLET_TYPE: ${WALLET_TYPE}
      POSTGRESQL_WALLET_HOST: ${POSTGRESQL_WALLET_HOST}
      POSTGRESQL_WALLET_PORT: ${POSTGRESQL_WALLET_PORT}
      POSTGRESQL_WALLET_USER: ${POSTGRESQL_USER}
      POSTGRESQL_WALLET_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_WALLET_ADMIN_PASSWORD: ${POSTGRESQL_ADMIN_PASSWORD}
      WALLET_ENCRYPTION_KEY: ${WALLET_ENCRYPTION_KEY}
      WALLET_SEED_VONX: ${WALLET_SEED_VONX:-}
      ISSUER_WALLET_DID: ${ISSUER_WALLET_DID}
      HTTP_FORCE_CLOSE_CONNECTIONS: "true"
    networks:
      - orgbook
      - myorg
    depends_on:
      - myorg-wallet-db
    entrypoint: >
      /bin/bash -c "
        echo sleeping ...;
        sleep 5;
        ../docker-entrypoint.sh;"
    volumes:
      - myorg-agent-wallet:/home/indy/.indy_client/wallet

  myorg-wallet-db:
    image: registry.access.redhat.com/rhscl/postgresql-95-rhel7:9.5
    environment:
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_ADMIN_PASSWORD=${POSTGRESQL_ADMIN_PASSWORD}
    networks:
      - orgbook
      - myorg
    ports:
      - 5435:5432
    volumes:
      - myorg-wallet-db:/var/lib/pgsql/data

volumes:
  caddyx-data:
  caddyx-logs:
  myorg-agent-wallet:
  myorg-wallet-db:

networks:
  myorg:
  orgbook:
    external:
      name: tob_tob
