# Documentation: https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

- name: my-registration.aviary-technologies-inc
  version: '1.0.0'
  description: The my-registration credential issued by aviary-technologies-inc
  endpoint: $ENDPOINT_URL
  path: /aviary-technologies-inc/my-registration
  # identify the attribute which identify the owning organization
  topic: corp_num
  # optionally identify the credential attribute to map to the TOB credential effective date
  effective_date: effective_date
  # optionally identify the credential attribute to map to the TOB credential revoked date
  revoked_date: expiry_date
  # optionally identify a dependant proof request
  #proof_request: dflow_registration
  attributes:
    corp_num:
      label_en: Registration ID
      description_en: Registration/Incorporation Number or Identifying Number
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: helper_uuid
      required: true
    registration_date:
      label_en: Registration Date
      description_en: Date of Registration, Incorporation, Continuation or Amalgamation
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: false
    entity_name:
      label_en: Name
      description_en: The legal name of entity
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_name
      required: true
    entity_name_effective:
      label_en: Name Effective Date
      description_en: Date current name became effective
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: true
    entity_address:
      label_en: Address
      description_en: The address of entity
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_address
      required: true
    entity_status:
      label_en: Registration Status
      description_en: Status of the entity (active or historical)
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_select
      required: true
    entity_status_effective:
      label_en: Status Effective Date
      description_en: Date status became effective
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: true
    entity_type:
      label_en: Registration Type
      description_en: Type of entity incorporated or registered
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    registered_jurisdiction:
      label_en: Registered Jurisdiction
      description_en: The jurisdiction an entity was created in
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: false
    effective_date:
      label_en: Credential Effective Date
      description_en: Date Credential is effective
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: true
    expiry_date:
      label_en: Credential Expiry Date
      description_en: Date Credential expired
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: false

- name: my-relationship.aviary-technologies-inc
  version: '1.0.0'
  description: The relationship between two organizations
  endpoint: $ENDPOINT_URL
  # identify the attribute which identify the owning organization
  topic: corp_num
  # optionally identify the credential attribute to map to the TOB credential effective date
  effective_date: effective_date
  # optionally identify the credential attribute to map to the TOB credential revoked date
  #revoked_date: expiry_date
  # optionally identify a dependant proof request
  proof_request: greenlight_registration
  path: /aviary-technologies-inc/my-relationship
  attributes:
    corp_num:
      label_en: Registration ID
      description_en: Unique identifer assigned to entity by registrar
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    associated_corp_num:
      label_en: Associated Registration ID
      description_en: Registry id(s) of associated organizations/individuals
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    associated_registration_name:
      label_en: Associated Registration Namwe
      description_en: Registered name of associated organizations/individuals
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: false
    relationship:
      label_en: Relationship
      description_en: Name of the relationship
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    relationship_description:
      label_en: Relationship Description
      description_en: Description of the relationship
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    relationship_status:
      label_en: Relationship Status
      description_en: Status of the relationship
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_select
      required: true
    relationship_status_effective:
      label_en: Relationship Status Effective
      description_en: Date the relationship became/becomes effective
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: false
    effective_date:
      label_en: Effective Date
      description_en: Date Credential is effective
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: true
    expiry_date:
      label_en: Credential Expiry Date
      description_en: Date Credential expires
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: false

- name: avalanche-permit.aviary-technologies-inc
  version: '1.0.0'
  description: The avalanche-permit credential issued by aviary-technologies-inc
  endpoint: $ENDPOINT_URL
  # identify the attribute which identify the owning organization
  topic: corp_num
  # optionally identify the credential attribute to map to the TOB credential effective date
  effective_date: effective_date
  # optionally identify the credential attribute to map to the TOB credential revoked date
  #revoked_date: expiry_date
  # optionally identify a dependant proof request
  proof_request: greenlight_registration
  path: /aviary-technologies-inc/avalanche-permit
  attributes:
    corp_num:
      label_en: Registration ID
      description_en: Registration/Incorporation Number or Identifying Number
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    entity_name:
      label_en: Name
      description_en: The legal name of entity
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_name
      required: true
    permit_id:
      label_en: Permit ID
      description_en: Permit Identifying Number
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: helper_uuid
      required: true
    permit_type:
      label_en: Permit Type
      description_en: Status of the permit
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_select
      required: true
    permit_issued_date:
      label_en: Permit Issued Date
      description_en: Date Permit is issued
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: true
    permit_status:
      label_en: Permit Status
      description_en: Status of the permit
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_select
      required: true
    effective_date:
      label_en: Credential Effective Date
      description_en: Date Credential is effective
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: true

### eof ###

